### ISSUE TITLE
Crash on trying to create a new folder in 'assets'

### ISSUE THREAD

**Issue by ShaneNZ** [conversionfoundry/breeze#196]
Tried to create a new folder, on w2.leftclick.co.nz:3000. Worked fine on a second go. Trace below:

NoMethodError in Breeze::Admin::Assets::FoldersController#new

undefined method `[]' for nil:NilClass
Rails.root: /home/admin/w2

Application Trace | Framework Trace | Full Trace
/home/admin/breeze/app/controllers/breeze/admin/assets/folders_controller.rb:23:in `new'
actionpack (3.2.12) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (3.2.12) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.12) lib/action_controller/metal/rendering.rb:10:in`process_action'
actionpack (3.2.12) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.12) lib/active_support/callbacks.rb:439:in`block (3 levels) in _run__4530459125068508203__process_action__547634472072851871__callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_541'
/home/admin/breeze/app/models/breeze/admin/user.rb:97:in`with_user'
/home/admin/breeze/app/controllers/breeze/admin/admin_controller.rb:48:in `set_current_user'
activesupport (3.2.12) lib/active_support/callbacks.rb:214:in`_conditional_callback_around_541'
activesupport (3.2.12) lib/active_support/callbacks.rb:438:in `block (2 levels) in _run__4530459125068508203__process_action__547634472072851871__callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:215:in`block in _conditional_callback_around_540'
/home/admin/breeze/lib/breeze.rb:45:in `with_domain'
/home/admin/breeze/app/controllers/breeze/controller.rb:56:in`set_domain_from_request'
activesupport (3.2.12) lib/active_support/callbacks.rb:214:in `_conditional_callback_around_540'
activesupport (3.2.12) lib/active_support/callbacks.rb:415:in`block in _run__4530459125068508203__process_action__547634472072851871__callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_539'
/home/admin/breeze/app/controllers/breeze/controller.rb:61:in`set_time_zone'
activesupport (3.2.12) lib/active_support/callbacks.rb:214:in `_conditional_callback_around_539'
activesupport (3.2.12) lib/active_support/callbacks.rb:414:in`_run__4530459125068508203__process_action__547634472072851871__callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.12) lib/active_support/callbacks.rb:385:in`_run_process_action_callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.12) lib/abstract_controller/callbacks.rb:17:in`process_action'
actionpack (3.2.12) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.12) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
activesupport (3.2.12) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.12) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
activesupport (3.2.12) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.12) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
actionpack (3.2.12) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
actionpack (3.2.12) lib/abstract_controller/base.rb:121:in`process'
actionpack (3.2.12) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.12) lib/action_controller/metal.rb:203:in`dispatch'
actionpack (3.2.12) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.12) lib/action_controller/metal.rb:246:in`block in action'
actionpack (3.2.12) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.12) lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
actionpack (3.2.12) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in`block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in`call'
actionpack (3.2.12) lib/action_dispatch/routing/route_set.rb:601:in `call'
railties (3.2.12) lib/rails/engine.rb:479:in`call'
railties (3.2.12) lib/rails/railtie/configurable.rb:30:in `method_missing'
journey (1.0.4) lib/journey/router.rb:68:in`block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in`call'
actionpack (3.2.12) lib/action_dispatch/routing/route_set.rb:601:in `call'
mongoid (3.0.22) lib/rack/mongoid/middleware/identity_map.rb:34:in`block in call'
mongoid (3.0.22) lib/mongoid/unit_of_work.rb:39:in `unit_of_work'
mongoid (3.0.22) lib/rack/mongoid/middleware/identity_map.rb:34:in`call'
warden (1.1.1) lib/warden/manager.rb:35:in `block in call'
warden (1.1.1) lib/warden/manager.rb:34:in`catch'
warden (1.1.1) lib/warden/manager.rb:34:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
rack (1.4.5) lib/rack/etag.rb:23:in `call'
rack (1.4.5) lib/rack/conditionalget.rb:25:in`call'
actionpack (3.2.12) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
actionpack (3.2.12) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.5) lib/rack/session/abstract/id.rb:210:in`context'
rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/cookies.rb:341:in`call'
actionpack (3.2.12) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.12) lib/active_support/callbacks.rb:405:in`_run__244839135565386931__call__1773199248501548157__callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.12) lib/active_support/callbacks.rb:385:in`_run_call_callbacks'
activesupport (3.2.12) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.12) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
actionpack (3.2.12) lib/action_dispatch/middleware/reloader.rb:65:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
actionpack (3.2.12) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
railties (3.2.12) lib/rails/rack/logger.rb:32:in `call_app'
railties (3.2.12) lib/rails/rack/logger.rb:16:in`block in call'
activesupport (3.2.12) lib/active_support/tagged_logging.rb:22:in `tagged'
railties (3.2.12) lib/rails/rack/logger.rb:16:in`call'
actionpack (3.2.12) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
rack (1.4.5) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.12) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
rack (1.4.5) lib/rack/lock.rb:15:in `call'
actionpack (3.2.12) lib/action_dispatch/middleware/static.rb:62:in`call'
railties (3.2.12) lib/rails/engine.rb:479:in `call'
railties (3.2.12) lib/rails/application.rb:223:in`call'
rack (1.4.5) lib/rack/content_length.rb:14:in `call'
rack (1.4.5) lib/rack/handler/webrick.rb:59:in`service'
/usr/local/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
/usr/local/lib/ruby/1.9.1/webrick/httpserver.rb:94:in`run'
/usr/local/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
Request

Parameters:

None
Show session dump

Show env dump

Response

Headers:

None

**Comment by isaacfreeman** [comment]
Can't reproduce this one. Have you managed to make it happen again?

**Comment by ShaneNZ** [comment]
No, and I can't reproduce it on any server I'm working with at the moment -
given the assets work for v2 I suggest we close it as a heisenbug, probably
removed in the course of other work.
